/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    colors: {
      black: "#000000",
      balckPhone: "#37363b",
      blue: "#435fcb",
      bluePhone: "#428aae",
      transparent: "transparent",
      white: "#ffffff",
      whitePhone: "#f2f2f2",
      purple: "#3f3cbb",
      midnight: "#121063",
      metal: "#565584",
      tahiti: "#3ab7bf",
      silver: "#ecebff",
      gray: "#808080",
      graphite: "#5c5b57",
      "bubble-gum": "#ff77e9",
      bermuda: "#78dcca",
      purple: "#b3abbd",
      olive: "#a4a28c",
      cream: "#f7f1e8",
      brown: "#964B00",
      lime: "#d9dfb7",
      silver: "#C0C0C0",
      Sierrablue: "#BFDAF7",
      Burgundy: "#63313A",
      Beige: "#F5F5DC",
      Green: "#60765f",
      red: "#FF0000",
    },
    extend: {},
  },
  plugins: [],
};
